#!/bin/bash
# WF 2020-03-14
# mvn clean compile assembly:single
# create fat jar and copy it to release directory
# recompile skip tests and signing
mvn -U clean install  -D skipTests -D gpg.skip -D createRelease=true -D createAssembly=true -Dmaven.javadoc.skip=true
