//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.01 at 07:50:59 PM CET 
//


package com.bitplan.mediawiki.japi.api;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.datatype.XMLGregorianCalendar;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="revisions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rev">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="contentformat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="contentmodel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="pageid" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="ns" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Page {

    @XmlAttribute(name = "pageid")
    protected Short pageid;
    @XmlAttribute(name = "ns")
    protected Byte ns;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlTransient
    protected List<Rev> revisions=new ArrayList<Rev>();
    @XmlElement
    protected Imageinfo imageinfo;

    /**
     * Gets the value of the revisions property.
     * 
     * @return list of {@link Rev }
     *     
     */
    @XmlElementWrapper(name="revisions")
    @XmlElement(name="rev", type=Rev.class)
    public List<Rev> getRevisions() {
        return revisions;
    }

    /**
     * Sets the value of the revisions property.
     * 
     * @param value list of  {@link Rev }
     *     
     */
    public void setRevisions(List<Rev> value) {
        this.revisions = value;
    }

    /**
     * Gets the value of the pageid property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPageid() {
        return pageid;
    }

    /**
     * Sets the value of the pageid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPageid(Short value) {
        this.pageid = value;
    }

    /**
     * Gets the value of the ns property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getNs() {
        return ns;
    }

    /**
     * Sets the value of the ns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setNs(Byte value) {
        this.ns = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }
    
    /**
     * Mediawiki 1_19
     */
  
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar touched;
    @XmlAttribute
    protected Byte lastrevid;
    @XmlAttribute
    protected Byte counter;
    @XmlAttribute
    protected Byte length;
    @XmlAttribute(name = "new")
    protected String _new;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar starttimestamp;
    @XmlAttribute
    protected String edittoken;
 

    /**
     * Gets the value of the touched property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTouched() {
        return touched;
    }

    /**
     * Sets the value of the touched property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTouched(XMLGregorianCalendar value) {
        this.touched = value;
    }

    /**
     * Gets the value of the lastrevid property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getLastrevid() {
        return lastrevid;
    }

    /**
     * Sets the value of the lastrevid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setLastrevid(Byte value) {
        this.lastrevid = value;
    }

    /**
     * Gets the value of the counter property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getCounter() {
        return counter;
    }

    /**
     * Sets the value of the counter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setCounter(Byte value) {
        this.counter = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setLength(Byte value) {
        this.length = value;
    }

    /**
     * Gets the value of the new property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNew() {
        return _new;
    }

    /**
     * Sets the value of the new property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNew(String value) {
        this._new = value;
    }

    /**
     * Gets the value of the starttimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStarttimestamp() {
        return starttimestamp;
    }

    /**
     * Sets the value of the starttimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStarttimestamp(XMLGregorianCalendar value) {
        this.starttimestamp = value;
    }

    /**
     * Gets the value of the edittoken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdittoken() {
        return edittoken;
    }

    /**
     * Sets the value of the edittoken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdittoken(String value) {
        this.edittoken = value;
    }
    
    /**
     * Ruft den Wert der imageinfo-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link Imageinfo }
     *     
     */
    public Imageinfo getImageinfo() {
        return imageinfo;
    }

    /**
     * Legt den Wert der imageinfo-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link Imageinfo }
     *     
     */
    public void setImageinfo(Imageinfo value) {
        this.imageinfo = value;
    }
}
