/**
 *
 * This file is part of the https://github.com/WolfgangFahl/Mediawiki-Japi open source project
 *
 * Copyright 2015-2021 BITPlan GmbH https://github.com/BITPlan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *  You may obtain a copy of the License at
 *
 *  http:www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.01 at 05:39:18 PM CET 
//


package com.bitplan.mediawiki.japi.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="contentformat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="contentmodel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
public class Rev {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "contentformat")
    protected String contentformat;
    @XmlAttribute(name = "contentmodel")
    protected String contentmodel;
    @XmlAttribute(name = "revid")
    protected Integer revid;
    @XmlAttribute(name = "parentid")
    protected Integer parentid;
    @XmlAttribute(name = "timestamp")
    protected String timestamp;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the contentformat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentformat() {
        return contentformat;
    }

    /**
     * Sets the value of the contentformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentformat(String value) {
        this.contentformat = value;
    }

    /**
     * Gets the value of the contentmodel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentmodel() {
        return contentmodel;
    }

    /**
     * Sets the value of the contentmodel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentmodel(String value) {
        this.contentmodel = value;
    }

    /**
     * @return the revid
     */
    public Integer getRevid() {
      return revid;
    }

    /**
     * @param revid the revid to set
     */
    public void setRevid(Integer revid) {
      this.revid = revid;
    }

    /**
     * @return the parentid
     */
    public Integer getParentid() {
      return parentid;
    }

    /**
     * @param parentid the parentid to set
     */
    public void setParentid(Integer parentid) {
      this.parentid = parentid;
    }

    /**
     * @return the timestamp
     */
    public String getTimestamp() {
      return timestamp;
    }

    /**
     * @param timestamp the timestamp to set
     */
    public void setTimestamp(String timestamp) {
      this.timestamp = timestamp;
    }

}
