/**
 *
 * This file is part of the https://github.com/WolfgangFahl/Mediawiki-Japi open source project
 *
 * Copyright 2015-2019 BITPlan GmbH https://github.com/BITPlan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *  You may obtain a copy of the License at
 *
 *  http:www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.04 at 09:15:47 PM MEZ 
//


package com.bitplan.mediawiki.japi.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="edittoken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
public class Tokens {

    @XmlValue
    protected String value;
    @XmlAttribute
    protected String edittoken;
    @XmlAttribute
    protected String deletetoken;
    @XmlAttribute(name = "csrftoken")
    protected String csrftoken;
    // since MW 1.27
    @XmlAttribute
    protected String createaccounttoken;
    // since MW 1.28
    @XmlAttribute
    protected String logintoken;
 
    /**
     * Ruft den Wert der csrftoken-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsrftoken() {
        return csrftoken;
    }

    /**
     * Legt den Wert der csrftoken-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsrftoken(String value) {
        this.csrftoken = value;
    }

    public String getCreateaccounttoken() {
      return createaccounttoken;
    }

    public void setCreateaccounttoken(String createaccounttoken) {
      this.createaccounttoken = createaccounttoken;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the edittoken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdittoken() {
        return edittoken;
    }

    /**
     * Sets the value of the edittoken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdittoken(String value) {
        this.edittoken = value;
    }

    /**
     * @return the deletetoken
     */
    public String getDeletetoken() {
      return deletetoken;
    }

    /**
     * @param deletetoken the deletetoken to set
     */
    public void setDeletetoken(String deletetoken) {
      this.deletetoken = deletetoken;
    }

    /**
     * return the login token
     * @return
     */
    public String getLogintoken() {
      return logintoken;
    }

}
