//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.04 at 09:15:47 PM MEZ 
//


package com.bitplan.mediawiki.japi.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="edittoken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
public class Tokens {

    @XmlValue
    protected String value;
    @XmlAttribute
    protected String edittoken;
    @XmlAttribute
    protected String deletetoken;
    @XmlAttribute(name = "csrftoken")
    protected String csrftoken;


    /**
     * Ruft den Wert der csrftoken-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsrftoken() {
        return csrftoken;
    }

    /**
     * Legt den Wert der csrftoken-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsrftoken(String value) {
        this.csrftoken = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the edittoken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdittoken() {
        return edittoken;
    }

    /**
     * Sets the value of the edittoken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdittoken(String value) {
        this.edittoken = value;
    }

    /**
     * @return the deletetoken
     */
    public String getDeletetoken() {
      return deletetoken;
    }

    /**
     * @param deletetoken the deletetoken to set
     */
    public void setDeletetoken(String deletetoken) {
      this.deletetoken = deletetoken;
    }

}
