//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 03:50:42 PM CET 
//


package com.bitplan.mediawiki.japi.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="rccontinue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="continue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class Continue {

    @XmlAttribute(name = "rccontinue")
    protected String rccontinue;
    @XmlAttribute(name = "continue")
    protected String _continue;

    /**
     * Gets the value of the rccontinue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRccontinue() {
        return rccontinue;
    }

    /**
     * Sets the value of the rccontinue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRccontinue(String value) {
        this.rccontinue = value;
    }

    /**
     * Gets the value of the continue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContinue() {
        return _continue;
    }

    /**
     * Sets the value of the continue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContinue(String value) {
        this._continue = value;
    }

}
