//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.05 at 05:20:14 PM CEST 
//


package com.bitplan.mediawiki.japi.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="s" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="toclevel" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="fromtitle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="byteoffset" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="anchor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s"
})
public class Sections {

    protected List<S> s;

    /**
     * Gets the value of the s property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the s property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link S }
     * 
     * 
     */
    public List<S> getS() {
        if (s == null) {
            s = new ArrayList<S>();
        }
        return this.s;
    }

}
