//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.02 at 01:58:10 AM CET 
//


package com.bitplan.jmediawiki.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="recentchanges">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rc" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ns" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                           &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="pageid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="revid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="old_revid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="rcid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="oldlen" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                           &lt;attribute name="newlen" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                           &lt;attribute name="new" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recentchanges"
})
public class Query {

    @XmlElement(required = true)
    protected Recentchanges recentchanges;

    /**
     * Gets the value of the recentchanges property.
     * 
     * @return
     *     possible object is
     *     {@link Recentchanges }
     *     
     */
    public Recentchanges getRecentchanges() {
        return recentchanges;
    }

    /**
     * Sets the value of the recentchanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recentchanges }
     *     
     */
    public void setRecentchanges(Recentchanges value) {
        this.recentchanges = value;
    }

}
